spring:
  application:
    name: emailVerification

  datasource:
    url: jdbc:mysql://rm-wz9nmsc90y064u9888o.mysql.rds.aliyuncs.com/registration?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: mailDemo1
    password: mailDemo1

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

server:
  error:
    include-message: always
    include-binding-errors: always
